/**
 * This is autogenerated Typst markup from a scene description created by
 * matplotlib in Python.
 *
 * Timestamp: 2024-11-23T14:08:29.
 */

#let draw-text(dx: 0pt, dy: 0pt, size: 10pt, alignment: center + horizon, baseline: false, angle: 0deg, body) = style(styles => {
  // In order to align a text properly, we need to configure bounding box of a
  // text.
  let top-edge = "cap-height"
  let bot-edge = "bounds"
  let valign = alignment.y;
  if baseline and valign == bottom {
    bot-edge = "baseline"
  }
  if baseline and valign == horizon {
    bot-edge = "baseline"
  }

  // Measure shape of text block.
  let content = text(size: size, top-edge: top-edge, bottom-edge: bot-edge, body)
  let shape = measure(content, styles)

  // Adjust horizontal position.
  let px = dx
  if alignment.x == left {
    // Do nothing.
  } else if alignment.x == center {
    px -= shape.width / 2
  } else if alignment.x == right {
    px -= shape.width
  }

  // Adjust vertical position.
  let py = dy
  if valign == top {
    // Do nothing.
  } else if valign == horizon {
    py -= shape.height / 2
  } else if valign == bottom {
    py -= shape.height
  }

  // Rotate text block if required. Note, that matplotlib supports two modes
  // for rotation while Typst allows to perform only the second one.
  if angle != 0deg {
    content = rotate(angle, origin: alignment, content)
  }

  // Finaly, place a content block in calculated displacement.
  place(dx: px, dy: py, content)
})

#block(
  {
    place(
      path(
        (0.0in, 4.8in),
        (6.4in, 4.8in),
        (6.4in, 0.0in),
        (0.0in, 0.0in),
        fill: rgb(
          100.0%,
          100.0%,
          100.0%,
          100.0%),
        stroke: stroke(
          paint: rgb(
            100.0%,
            100.0%,
            100.0%,
            100.0%),
          thickness: 0.0pt,
          cap: "butt",
          join: "miter"),
        closed: true),
      dx: 0in,
      dy: 0in)
    place(
      path(
        (0.8in, 2.256in),
        (5.76in, 2.256in),
        (5.76in, 0.5759999999999996in),
        (0.8in, 0.5759999999999996in),
        fill: rgb(
          100.0%,
          100.0%,
          100.0%,
          100.0%),
        stroke: stroke(
          paint: rgb(
            0.0%,
            0.0%,
            0.0%,
            0.0%),
          thickness: 0.0pt,
          cap: "butt",
          join: "miter"),
        closed: true),
      dx: 0in,
      dy: 0in)
    place(
      path(
        (1.0254545454545454in, 2.256in),
        (1.0254545454545454in, 2.291in),
        fill: rgb(
          0.0%,
          0.0%,
          0.0%,
          100.0%),
        stroke: stroke(
          paint: rgb(
            0.0%,
            0.0%,
            0.0%,
            100.0%),
          thickness: 0.8pt,
          cap: "butt",
          join: "round")),
      dx: 0in,
      dy: 0in)
    draw-text(
      [0.0],
      dx: 1.0254545454545454in,
      dy: 2.353222222222222in,
      size: 10.0pt,
      alignment: center + top,
      baseline: false,
      angle: 360.0deg)
    place(
      path(
        (1.589090909090909in, 2.256in),
        (1.589090909090909in, 2.291in),
        fill: rgb(
          0.0%,
          0.0%,
          0.0%,
          100.0%),
        stroke: stroke(
          paint: rgb(
            0.0%,
            0.0%,
            0.0%,
            100.0%),
          thickness: 0.8pt,
          cap: "butt",
          join: "round")),
      dx: 0in,
      dy: 0in)
    draw-text(
      [0.5],
      dx: 1.589090909090909in,
      dy: 2.353222222222222in,
      size: 10.0pt,
      alignment: center + top,
      baseline: false,
      angle: 360.0deg)
    place(
      path(
        (2.1527272727272724in, 2.256in),
        (2.1527272727272724in, 2.291in),
        fill: rgb(
          0.0%,
          0.0%,
          0.0%,
          100.0%),
        stroke: stroke(
          paint: rgb(
            0.0%,
            0.0%,
            0.0%,
            100.0%),
          thickness: 0.8pt,
          cap: "butt",
          join: "round")),
      dx: 0in,
      dy: 0in)
    draw-text(
      [1.0],
      dx: 2.1527272727272724in,
      dy: 2.353222222222222in,
      size: 10.0pt,
      alignment: center + top,
      baseline: false,
      angle: 360.0deg)
    place(
      path(
        (2.7163636363636363in, 2.256in),
        (2.7163636363636363in, 2.291in),
        fill: rgb(
          0.0%,
          0.0%,
          0.0%,
          100.0%),
        stroke: stroke(
          paint: rgb(
            0.0%,
            0.0%,
            0.0%,
            100.0%),
          thickness: 0.8pt,
          cap: "butt",
          join: "round")),
      dx: 0in,
      dy: 0in)
    draw-text(
      [1.5],
      dx: 2.7163636363636363in,
      dy: 2.353222222222222in,
      size: 10.0pt,
      alignment: center + top,
      baseline: false,
      angle: 360.0deg)
    place(
      path(
        (3.28in, 2.256in),
        (3.28in, 2.291in),
        fill: rgb(
          0.0%,
          0.0%,
          0.0%,
          100.0%),
        stroke: stroke(
          paint: rgb(
            0.0%,
            0.0%,
            0.0%,
            100.0%),
          thickness: 0.8pt,
          cap: "butt",
          join: "round")),
      dx: 0in,
      dy: 0in)
    draw-text(
      [2.0],
      dx: 3.28in,
      dy: 2.353222222222222in,
      size: 10.0pt,
      alignment: center + top,
      baseline: false,
      angle: 360.0deg)
    place(
      path(
        (3.8436363636363637in, 2.256in),
        (3.8436363636363637in, 2.291in),
        fill: rgb(
          0.0%,
          0.0%,
          0.0%,
          100.0%),
        stroke: stroke(
          paint: rgb(
            0.0%,
            0.0%,
            0.0%,
            100.0%),
          thickness: 0.8pt,
          cap: "butt",
          join: "round")),
      dx: 0in,
      dy: 0in)
    draw-text(
      [2.5],
      dx: 3.8436363636363637in,
      dy: 2.353222222222222in,
      size: 10.0pt,
      alignment: center + top,
      baseline: false,
      angle: 360.0deg)
    place(
      path(
        (4.407272727272727in, 2.256in),
        (4.407272727272727in, 2.291in),
        fill: rgb(
          0.0%,
          0.0%,
          0.0%,
          100.0%),
        stroke: stroke(
          paint: rgb(
            0.0%,
            0.0%,
            0.0%,
            100.0%),
          thickness: 0.8pt,
          cap: "butt",
          join: "round")),
      dx: 0in,
      dy: 0in)
    draw-text(
      [3.0],
      dx: 4.407272727272727in,
      dy: 2.353222222222222in,
      size: 10.0pt,
      alignment: center + top,
      baseline: false,
      angle: 360.0deg)
    place(
      path(
        (4.970909090909091in, 2.256in),
        (4.970909090909091in, 2.291in),
        fill: rgb(
          0.0%,
          0.0%,
          0.0%,
          100.0%),
        stroke: stroke(
          paint: rgb(
            0.0%,
            0.0%,
            0.0%,
            100.0%),
          thickness: 0.8pt,
          cap: "butt",
          join: "round")),
      dx: 0in,
      dy: 0in)
    draw-text(
      [3.5],
      dx: 4.970909090909091in,
      dy: 2.353222222222222in,
      size: 10.0pt,
      alignment: center + top,
      baseline: false,
      angle: 360.0deg)
    place(
      path(
        (5.534545454545454in, 2.256in),
        (5.534545454545454in, 2.291in),
        fill: rgb(
          0.0%,
          0.0%,
          0.0%,
          100.0%),
        stroke: stroke(
          paint: rgb(
            0.0%,
            0.0%,
            0.0%,
            100.0%),
          thickness: 0.8pt,
          cap: "butt",
          join: "round")),
      dx: 0in,
      dy: 0in)
    draw-text(
      [4.0],
      dx: 5.534545454545454in,
      dy: 2.353222222222222in,
      size: 10.0pt,
      alignment: center + top,
      baseline: false,
      angle: 360.0deg)
    draw-text(
      [Time],
      dx: 3.28in,
      dy: 2.5054965277777774in,
      size: 10.0pt,
      alignment: center + top,
      baseline: false,
      angle: 360.0deg)
    place(
      path(
        (0.8in, 2.119253426762573in),
        (0.765in, 2.119253426762573in),
        fill: rgb(
          0.0%,
          0.0%,
          0.0%,
          100.0%),
        stroke: stroke(
          paint: rgb(
            0.0%,
            0.0%,
            0.0%,
            100.0%),
          thickness: 0.8pt,
          cap: "butt",
          join: "round")),
      dx: 0in,
      dy: 0in)
    draw-text(
      [