/**
 * This is autogenerated Typst markup from a scene description created by
 * matplotlib in Python.
 *
 * Timestamp: 2024-11-21T12:39:49.
 */

#let draw-text(dx: 0pt, dy: 0pt, size: 10pt, alignment: center + horizon, baseline: false, angle: 0deg, body) = style(styles => {
  // In order to align a text properly, we need to configure bounding box of a
  // text.
  let top-edge = "cap-height"
  let bot-edge = "bounds"
  let valign = alignment.y;
  if baseline and valign == bottom {
    bot-edge = "baseline"
  }
  if baseline and valign == horizon {
    bot-edge = "baseline"
  }

  // Measure shape of text block.
  let content = text(size: size, top-edge: top-edge, bottom-edge: bot-edge, body)
  let shape = measure(content, styles)

  // Adjust horizontal position.
  let px = dx
  if alignment.x == left {
    // Do nothing.
  } else if alignment.x == center {
    px -= shape.width / 2
  } else if alignment.x == right {
    px -= shape.width
  }

  // Adjust vertical position.
  let py = dy
  if valign == top {
    // Do nothing.
  } else if valign == horizon {
    py -= shape.height / 2
  } else if valign == bottom {
    py -= shape.height
  }

  // Rotate text block if required. Note, that matplotlib supports two modes
  // for rotation while Typst allows to perform only the second one.
  if angle != 0deg {
    content = rotate(angle, origin: alignment, content)
  }

  // Finaly, place a content block in calculated displacement.
  place(dx: px, dy: py, content)
})

#block(
  {
    place(
      path(
        (0.0in, 4.8in),
        (6.0in, 4.8in),
        (6.0in, 0.0in),
        (0.0in, 0.0in),
        fill: rgb(
          100.0%,
          100.0%,
          100.0%,
          100.0%),
        stroke: stroke(
          paint: rgb(
            100.0%,
            100.0%,
            100.0%,
            100.0%),
          thickness: 0.0pt,
          cap: "butt",
          join: "miter"),
        closed: true),
      dx: 0in,
      dy: 0in)
    place(
      path(
        (0.75in, 4.272in),
        (5.4in, 4.272in),
        (5.4in, 0.5759999999999996in),
        (0.75in, 0.5759999999999996in),
        fill: rgb(
          100.0%,
          100.0%,
          100.0%,
          100.0%),
        stroke: stroke(
          paint: rgb(
            0.0%,
            0.0%,
            0.0%,
            0.0%),
          thickness: 0.0pt,
          cap: "butt",
          join: "miter"),
        closed: true),
      dx: 0in,
      dy: 0in)
    place(
      path(
        (0.75in, 4.272in),
        (0.75in, 0.5759999999999996in),
        fill: none,
        stroke: stroke(
          paint: rgb(
            69.01960784313725%,
            69.01960784313725%,
            69.01960784313725%,
            100.0%),
          thickness: 0.8pt,
          cap: "square",
          join: "round")),
      dx: 0in,
      dy: 0in)
    place(
      path(
        (0.75in, 4.272in),
        (0.75in, 4.3069999999999995in),
        fill: rgb(
          0.0%,
          0.0%,
          0.0%,
          100.0%),
        stroke: stroke(
          paint: rgb(
            0.0%,
            0.0%,
            0.0%,
            100.0%),
          thickness: 0.8pt,
          cap: "butt",
          join: "round")),
      dx: 0in,
      dy: 0in)
    draw-text(
      [0.0],
      dx: 0.75in,
      dy: 4.369222222222222in,
      size: 10.0pt,
      alignment: center + top,
      baseline: false,
      angle: 360.0deg)
    place(
      path(
        (1.68in, 4.272in),
        (1.68in, 0.5759999999999996in),
        fill: none,
        stroke: stroke(
          paint: rgb(
            69.01960784313725%,
            69.01960784313725%,
            69.01960784313725%,
            100.0%),
          thickness: 0.8pt,
          cap: "square",
          join: "round")),
      dx: 0in,
      dy: 0in)
    place(
      path(
        (1.68in, 4.272in),
        (1.68in, 4.3069999999999995in),
        fill: rgb(
          0.0%,
          0.0%,
          0.0%,
          100.0%),
        stroke: stroke(
          paint: rgb(
            0.0%,
            0.0%,
            0.0%,
            100.0%),
          thickness: 0.8pt,
          cap: "butt",
          join: "round")),
      dx: 0in,
      dy: 0in)
    draw-text(
      [0.2],
      dx: 1.68in,
      dy: 4.369222222222222in,
      size: 10.0pt,
      alignment: center + top,
      baseline: false,
      angle: 360.0deg)
    place(
      path(
        (2.61in, 4.272in),
        (2.61in, 0.5759999999999996in),
        fill: none,
        stroke: stroke(
          paint: rgb(
            69.01960784313725%,
            69.01960784313725%,
            69.01960784313725%,
            100.0%),
          thickness: 0.8pt,
          cap: "square",
          join: "round")),
      dx: 0in,
      dy: 0in)
    place(
      path(
        (2.61in, 4.272in),
        (2.61in, 4.3069999999999995in),
        fill: rgb(
          0.0%,
          0.0%,
          0.0%,
          100.0%),
        stroke: stroke(
          paint: rgb(
            0.0%,
            0.0%,
            0.0%,
            100.0%),
          thickness: 0.8pt,
          cap: "butt",
          join: "round")),
      dx: 0in,
      dy: 0in)
    draw-text(
      [0.4],
      dx: 2.61in,
      dy: 4.369222222222222in,
      size: 10.0pt,
      alignment: center + top,
      baseline: false,
      angle: 360.0deg)
    place(
      path(
        (3.5400000000000005in, 4.272in),
        (3.5400000000000005in, 0.5759999999999996in),
        fill: none,
        stroke: stroke(
          paint: rgb(
            69.01960784313725%,
            69.01960784313725%,
            69.01960784313725%,
            100.0%),
          thickness: 0.8pt,
          cap: "square",
          join: "round")),
      dx: 0in,
      dy: 0in)
    place(
      path(
        (3.5400000000000005in, 4.272in),
        (3.5400000000000005in, 4.3069999999999995in),
        fill: rgb(
          0.0%,
          0.0%,
          0.0%,
          100.0%),
        stroke: stroke(
          paint: rgb(
            0.0%,
            0.0%,
            0.0%,
            100.0%),
          thickness: 0.8pt,
          cap: "butt",
          join: "round")),
      dx: 0in,
      dy: 0in)
    draw-text(
      [0.6],
      dx: 3.5400000000000005in,
      dy: 4.369222222222222in,
      size: 10.0pt,
      alignment: center + top,
      baseline: false,
      angle: 360.0deg)
    place(
      path(
        (4.47in, 4.272in),
        (4.47in, 0.5759999999999996in),
        fill: none,
        stroke: stroke(
          paint: rgb(
            69.01960784313725%,
            69.01960784313725%,
            69.01960784313725%,
            100.0%),
          thickness: 0.8pt,
          cap: "square",
          join: "round")),
      dx: 0in,
      dy: 0in)
    place(
      path(
        (4.47in, 4.272in),
        (4.47in, 4.3069999999999995in),
        fill: rgb(
          0.0%,
          0.0%,
          0.0%,
          100.0%),
        stroke: stroke(
          paint: rgb(
            0.0%,
            0.0%,
            0.0%,
            100.0%),
          thickness: 0.8pt,
          cap: "butt",
          join: "round")),
      dx: 0in,
      dy: 0in)
    draw-text(
      [0.8],
      dx: 4.47in,
      dy: 4.369222222222222in,
      size: 10.0pt,
      alignment: center + top,
      baseline: false,
      angle: 360.0deg)
    place(
      path(
        (5.4in, 4.272in),
        (5.4in, 0.5759999999999996in),
        fill: none,
        stroke: stroke(
          paint: rgb(
            69.01960784313725%,
            69.01960784313725%,
            69.01960784313725%,
            100.0%),
          thickness: 0.8pt,
          cap: "square",
          join: "round")),
      dx: 0in,
      dy: 0in)
    place(
      path(
        (5.4in, 4.272in),
        (5.4in, 4.3069999999999995in),
        fill: rgb(
          0.0%,
          0.0%,
          0.0%,
          100.0%),
        stroke: stroke(
          paint: rgb(
            0.0%,
            0.0%,
            0.0%,
            100.0%),
          thickness: 0.8pt,
          cap: "butt",
          join: "round")),
      dx: 0in,
      dy: 0in)
    draw-text(
      [1.0],
      dx: 5.4in,
      dy: 4.369222222222222in,
      size: 10.0pt,
      alignment: center + top,
      baseline: false,
      angle: 360.0deg)
    draw-text(
      [$t_{parallel}$],
      dx: 3.075in,
      dy: 4.521496527777778in,
      size: 10.0pt,
      alignment: center + top,
      baseline: false,
      angle: 360.0deg)
    place(
      path(
        (0.75in, 4.104in),
        (5.4in, 4.104in),
        fill: none,
        stroke: stroke(
          paint: rgb(
            69.01960784313725%,
            69.01960784313725%,
            69.01960784313725%,
            100.0%),
          thickness: 0.8pt,
          cap: "square",
          join: "round")),
      dx: 0in,
      dy: 0in)
    place(
      path(
        (0.75in, 4.104in),
        (0.715in, 4.104in),
        fill: rgb(
          0.0%,
          0.0%,
          0.0%,
          100.0%),
        stroke: stroke(
          paint: rgb(
            0.0%,
            0.0%,
            0.0%,
            100.0%),
          thickness: 0.8pt,
          cap: "butt",
          join: "round")),
      dx: 0in,
      dy: 0in)
    draw-text(
      [$2^0$],
      dx: 0.6527777777777777in,
      dy: 4.104in,
      size: 10.0pt,
      alignment: right + horizon,
      baseline: true,
      angle: 360.0deg)
    place(
      path(
        (0.75in, 3.5439999999999996in),
        (5.4in, 3.5439999999999996in),
        fill: none,
        stroke: stroke(
          paint: rgb(
            69.01960784313725%,
            69.01960784313725%,
            69.01960784313725%,
            100.0%),
          thickness: 0.8pt,
          cap: "square",
          join: "round")),
      dx: 0in,
      dy: 0in)
    place(
      path(
        (0.75in, 3.5439999999999996in),
        (0.715in, 3.5439999999999996in),
        fill: rgb(
          0.0%,
          0.0%,
          0.0%,
          100.0%),
        stroke: stroke(
          paint: rgb(
            0.0%,
            0.0%,
            0.0%,
            100.0%),
          thickness: 0.8pt,
          cap: "butt",
          join: "round")),
      dx: 0in,
      dy: 0in)
    draw-text(
      [$2^1$],
      dx: 0.6527777777777777in,
      dy: 3.5439999999999996in,
      size: 10.0pt,
      alignment: right + horizon,
      baseline: true,
      angle: 360.0deg)
    place(
      path(
        (0.75in, 2.984in),
        (5.4in, 2.984in),
        fill: none,
        stroke: stroke(
          paint: rgb(
            69.01960784313725%,
            69.01960784313725%,
            69.01960784313725%,
            100.0%),
          thickness: 0.8pt,
          cap: "square",
          join: "round")),
      dx: 0in,
      dy: 0in)
    place(
      path(
        (0.75in, 2.984in),
        (0.715in, 2.984in),
        fill: rgb(
          0.0%,
          0.0%,
          0.0%,
          100.0%),
        stroke: stroke(
          paint: rgb(
            0.0%,
            0.0%,
            0.0%,
            100.0%),
          thickness: 0.8pt,
          cap: "butt",
          join: "round")),
      dx: 0in,
      dy: 0in)
    draw-text(
      [$2^2$],
      dx: 0.6527777777777777in,
      dy: 2.984in,
      size: 10.0pt,
      alignment: right + horizon,
      baseline: true,
      angle: 360.0deg)
    place(
      path(
        (0.75in, 2.4240000000000004in),
        (5.4in, 2.4240000000000004in),
        fill: none,
        stroke: stroke(
          paint: rgb(
            69.01960784313725%,
            69.01960784313725%,
            69.01960784313725%,
            100.0%),
          thickness: 0.8pt,
          cap: "square",
          join: "round")),
      dx: 0in,
      dy: 0in)
    place(
      path(
        (0.75in, 2.4240000000000004in),
        (0.715in, 2.4240000000000004in),
        fill: rgb(
          0.0%,
          0.0%,
          0.0%,
          100.0%),
        stroke: stroke(
          paint: rgb(
            0.0%,
            0.0%,
            0.0%,
            100.0%),
          thickness: 0.8pt,
          cap: "butt",
          join: "round")),
      dx: 0in,
      dy: 0in)
    draw-text(
      [$2^3$],
      dx: 0.6527777777777777in,
      dy: 2.4240000000000004in,
      size: 10.0pt,
      alignment: right + horizon,
      baseline: true,
      angle: 360.0deg)
    place(
      path(
        (0.75in, 1.8640000000000003in),
        (5.4in, 1.8640000000000003in),
        fill: none,
        stroke: stroke(
          paint: rgb(
            69.01960784313725%,
            69.01960784313725%,
            69.01960784313725%,
            100.0%),
          thickness: 0.8pt,
          cap: "square",
          join: "round")),
      dx: 0in,
      dy: 0in)
    place(
      path(
        (0.75in, 1.8640000000000003in),
        (0.715in, 1.8640000000000003in),
        fill: rgb(
          0.0%,
          0.0%,
          0.0%,
          100.0%),
        stroke: stroke(
          paint: rgb(
            0.0%,
            0.0%,
            0.0%,
            100.0%),
          thickness: 0.8pt,
          cap: "butt",
          join: "round")),
      dx: 0in,
      dy: 0in)
    draw-text(
      [$2^4$],
      dx: 0.6527777777777777in,
      dy: 1.8640000000000003in,
      size: 10.0pt,
      alignment: right + horizon,
      baseline: true,
      angle: 360.0deg)
    place(
      path(
        (0.75in, 1.3040000000000007in),
        (5.4in, 1.3040000000000007in),
        fill: none,
        stroke: stroke(
          paint: rgb(
            69.01960784313725%,
            69.01960784313725%,
            69.01960784313725%,
            100.0%),
          thickness: 0.8pt,
          cap: "square",
          join: "round")),
      dx: 0in,
      dy: 0in)
    place(
      path(
        (0.75in, 1.3040000000000007in),
        (0.715in, 1.3040000000000007in),
        fill: rgb(
          0.0%,
          0.0%,
          0.0%,
          100.0%),
        stroke: stroke(
          paint: rgb(
            0.0%,
            0.0%,
            0.0%,
            100.0%),
          thickness: 0.8pt,
          cap: "butt",
          join: "round")),
      dx: 0in,
      dy: 0in)
    draw-text(
      [$2^5$],
      dx: 0.6527777777777777in,
      dy: 1.3040000000000007in,
      size: 10.0pt,
      alignment: right + horizon,
      baseline: true,
      angle: 360.0deg)
    place(
      path(
        (0.75in, 0.7440000000000007in),
        (5.4in, 0.7440000000000007in),
        fill: none,
        stroke: stroke(
          paint: rgb(
            69.01960784313725%,
            69.01960784313725%,
            69.01960784313725%,
            100.0%),
          thickness: 0.8pt,
          cap: "square",
          join: "round")),
      dx: 0in,
      dy: 0in)
    place(
      path(
        (0.75in, 0.7440000000000007in),
        (0.715in, 0.7440000000000007in),
        fill: rgb(
          0.0%,
          0.0%,
          0.0%,
          100.0%),
        stroke: stroke(
          paint: rgb(
            0.0%,
            0.0%,
            0.0%,
            100.0%),
          thickness: 0.8pt,
          cap: "butt",
          join: "round")),
      dx: 0in,
      dy: 0in)
    draw-text(
      [$2^6$],
      dx: 0.6527777777777777in,
      dy: 0.7440000000000007in,
      size: 10.0pt,
      alignment: right + horizon,
      baseline: true,
      angle: 360.0deg)
    draw-text(
      [Speedup $S_{overall}$],
      dx: 0.47722222222222216in,
      dy: 2.4240000000000004in,
      size: 10.0pt,
      alignment: center + bottom,
      baseline: false,
      angle: 270.0deg)
    place(
      path(
        (0.75in, 4.104in),
        (1.071171171171171in, 4.0610259117611225in),
        (1.3737237237237239in, 4.018338942401813in),
        (1.6623123123123122in, 3.975406501362715in),
        (1.9369369369369371in, 3.9323175337848495in),
        (2.1975975975975977in, 3.889177718931662in),
        (2.4442942942942945in, 3.846111527313866in),
        (2.677027027027027in, 3.8032643067518257in),
        (2.900450450450451in, 3.759876205252304in),
        (3.10990990990991in, 3.716968287554673in),
        (3.3100600600600605in, 3.6737220009322105in),
        (3.5009009009009007in, 3.63021276453136in),
        (3.6824324324324325in, 3.586531357810647in),
        (3.8546546546546545in, 3.5427860114576823in),
        (4.017567567567568in, 3.4991046047369694in),
        (4.171171171171171in, 3.4556369023483837in),
        (4.315465465465466in, 3.412556730425947in),
        (4.455105105105106in, 3.3685580610964454in),
        (4.585435435435436in, 3.325211539032506in),
        (4.711111111111111in, 3.2810882413513163in),
        (4.8321321321321316in, 3.2361928460882856in),
        (4.943843843843844in, 3.192412787529988in),
        (5.050900900900901in, 3.1481063059441308in),
        (5.153303303303303in, 3.1033240553102184in),
        (5.251051051051051in, 3.058129600549826in),
        (5.344144144144144in, 3.0126015433727913in),
        (5.4in, 2.984in),
        (5.4in, 2.984in),
        fill: none,
        stroke: stroke(
          paint: rgb(
            12.156862745098039%,
            46.666666666666664%,
            70.58823529411765%,
            100.0%),
          thickness: 1.5pt,
          cap: "square",
          join: "round")),
      dx: 0in,
      dy: 0in)
    place(
      path(
        (0.75in, 4.104in),
        (1.006006006006006in, 4.061185814626146in),
        (1.248048048048048in, 4.018507520226712in),
        (1.4807807807807807in, 3.975228684871869in),
        (1.6995495495495496in, 3.9323175337848495in),
        (1.9090090090090088in, 3.8889798716861774in),
        (2.109159159159159in, 3.845276478947124in),
        (2.2953453453453454in, 3.8023837516533234in),
        (2.472222222222222in, 3.759411756131782in),
        (2.6397897897897895in, 3.716478497165075in),
        (2.8027027027027027in, 3.6724295526916144in),
        (2.9563063063063066in, 3.628575663215571in),
        (3.100600600600601in, 3.5850914906982894in),
        (3.24024024024024in, 3.540657132168163in),
        (3.37057057057057in, 3.49685728973326in),
        (3.4962462462462462in, 3.4522465942976606in),
        (3.6126126126126126in, 3.408621809451933in),
        (3.7243243243243245in, 3.364402334630813in),
        (3.831381381381381in, 3.3196259715396534in),
        (3.9337837837837837in, 3.2743415698031795in),
        (4.031531531531531in, 3.2286109760422046in),
        (4.124624624624625in, 3.182511237460077in),
        (4.213063063063063in, 3.1361370615002935in),
        (4.296846846846846in, 3.0896035166727547in),
        (4.375975975975976in, 3.043048935226895in),
        (4.45045045045045in, 2.996637943866954in),
        (4.52027027027027in, 2.95056450217041in),
        (4.585435435435436in, 2.9050547684621377in),
        (4.6506006006006in, 2.8568276261317793in),
        (4.711111111111111in, 2.8093113564637457in),
        (4.766966966966967in, 2.7628224513687307in),
        (4.822822822822823in, 2.713494260629661in),
        (4.874024024024024in, 2.6654682298951355in),
        (4.925225225225225in, 2.6144058541676594in),
        (4.971771771771771in, 2.5650072656343212in),
        (5.018318318318318in, 2.5123904187417074in),
        (5.06021021021021in, 2.4619147211174988in),
        (5.102102102102102in, 2.408074056106095in),
        (5.143993993993994in, 2.350387521968501in),
        (5.181231231231232in, 2.2954065013627156in),
        (5.218468468468468in, 2.2364088212808273in),
        (5.251051051051051in, 2.1809966628117237in),
        (5.283633633633633in, 2.1215022357743822in),
        (5.316216216216216in, 2.0572758721872657in),
        (5.348798798798798in, 1.9874993060648842in),
        (5.3767267267267265in, 1.922484949708077in),
        (5.4in, 1.8640000000000003in),
        (5.4in, 1.8640000000000003in),
        fill: none,
        stroke: stroke(
          paint: rgb(
            100.0%,
            49.80392156862745%,
            5.490196078431373%,
            100.0%),
          thickness: 1.5pt,
          cap: "square",
          join: "round")),
      dx: 0in,
      dy: 0in)
    place(
      path(
        (0.75in, 4.104in),
        (0.9966966966966967in, 4.06066601455884in),
        (1.2294294294294295in, 4.01753771701918in),
        (1.4481981981981982in, 3.9747839723473484in),
        (1.6576576576576576in, 3.931613963921611in),
        (1.857807807807808in, 3.8880889590178063in),
        (2.043993993993994in, 3.8453809072059006in),
        (2.2208708708708707in, 3.8026039804192773in),
        (2.393093093093093in, 3.758656456382573in),
        (2.5560060060060064in, 3.7147618886697287in),
        (2.7096096096096094in, 3.671070253113589in),
        (2.853903903903904in, 3.6277558668764343in),
        (2.993543543543544in, 3.5835046673237967in),
        (3.1238738738738743in, 3.5398954565928458in),
        (3.2495495495495494in, 3.4954897923400816in),
        (3.3659159159159158in, 3.4520767048589316in),
        (3.4776276276276277in, 3.4080837413515264in),
        (3.5846846846846847in, 3.363549659910084in),
        (3.687087087087087in, 3.3185242542113134in),
        (3.784834834834834in, 3.2730702725732765in),
        (3.8779279279279275in, 3.227265581521634in),
        (3.9663663663663664in, 3.181205573258781in),
        (4.0501501501501505in, 3.135005799859826in),
        (4.129279279279279in, 3.088804792709629in),
        (4.2037537537537535in, 3.0427669916808826in),
        (4.273573573573574in, 2.997085663037679in),
        (4.343393393393393in, 2.9486657722179768in),
        (4.408558558558559in, 2.900695836992818in),
        (4.469069069069069in, 2.853448364136245in),
        (4.529579579579579in, 2.8032652349034857in),
        (4.585435435435436in, 2.7540015186294102in),
        (4.636636636636637in, 2.7060421527665897in),
        (4.687837837837838in, 2.6550551341433586in),
        (4.734384384384384in, 2.605734115569105in),
        (4.780930930930931in, 2.5532052697199052in),
        (4.822822822822823in, 2.5028195426220097in),
        (4.864714714714715in, 2.449081236178229in),
        (4.906606606606607in, 2.3915121963821835in),
        (4.943843843843844in, 2.336651226678605in),
        (4.981081081081081in, 2.2777917649352073in),
        (5.018318318318318in, 2.214304814438759in),
        (5.050900900900901in, 2.15434156980318in),
        (5.083483483483484in, 2.08956846298557in),
        (5.111411411411411in, 2.029590069855943in),
        (5.13933933933934in, 1.9647992851350358in),
        (5.167267267267267in, 1.8943559614843695in),
        (5.195195195195194in, 1.8171787177155778in),
        (5.218468468468468in, 1.7467061152477887in),
        (5.241741741741741in, 1.669493721521346in),
        (5.265015015015015in, 1.584114734223252in),
        (5.288288288288288in, 1.4886350494682858in),
        (5.306906906906907in, 1.4031915050563737in),
        (5.325525525525526in, 1.307631058799311in),
        (5.344144144144144in, 1.1992320905437248in),
        (5.362762762762762in, 1.0740015186294123in),
        (5.3767267267267265in, 0.9654288678167506in),
        (5.390690690690691in, 0.839966314254708in),
        (5.4in, 0.7440000000000007in),
        (5.4in, 0.7440000000000007in),
        fill: none,
        stroke: stroke(
          paint: rgb(
            17.254901960784313%,
            62.745098039215684%,
            17.254901960784313%,
            100.0%),
          thickness: 1.5pt,
          cap: "square",
          join: "round")),
      dx: 0in,
      dy: 0in)
    place(
      path(
        (0.75in, 4.272in),
        (0.75in, 0.5759999999999996in),
        fill: none,
        stroke: stroke(
          paint: rgb(
            0.0%,
            0.0%,
            0.0%,
            100.0%),
          thickness: 0.8pt,
          cap: "square",
          join: "miter")),
      dx: 0in,
      dy: 0in)
    place(
      path(
        (5.4in, 4.272in),
        (5.4in, 0.5759999999999996in),
        fill: none,
        stroke: stroke(
          paint: rgb(
            0.0%,
            0.0%,
            0.0%,
            100.0%),
          thickness: 0.8pt,
          cap: "square",
          join: "miter")),
      dx: 0in,
      dy: 0in)
    place(
      path(
        (0.75in, 4.272in),
        (5.4in, 4.272in),
        fill: none,
        stroke: stroke(
          paint: rgb(
            0.0%,
            0.0%,
            0.0%,
            100.0%),
          thickness: 0.8pt,
          cap: "square",
          join: "miter")),
      dx: 0in,
      dy: 0in)
    place(
      path(
        (0.75in, 0.5759999999999996in),
        (5.4in, 0.5759999999999996in),
        fill: none,
        stroke: stroke(
          paint: rgb(
            0.0%,
            0.0%,
            0.0%,
            100.0%),
          thickness: 0.8pt,
          cap: "square",
          join: "miter")),
      dx: 0in,
      dy: 0in)
    place(
      path(
        (0.82in, 1.09615625in),
        (1.56765625in, 1.09615625in),
        ((1.58765625in, 1.07615625in), (0.0in, 0.020000000000000018in)),
        (1.58765625in, 0.6459999999999999in),
        ((1.56765625in, 0.6260000000000003in), (0.020000000000000018in, 0.0in)),
        (0.82in, 0.6260000000000003in),
        ((0.8in, 0.6459999999999999in), (0.0in, -0.019999999999999574in)),
        (0.8in, 1.07615625in),
        ((0.82in, 1.09615625in), (-0.019999999999999907in, 0.0in)),
        fill: rgb(
          100.0%,
          100.0%,
          100.0%,
          80.0%),
        stroke: stroke(
          paint: rgb(
            80.0%,
            80.0%,
            80.0%,
            80.0%),
          thickness: 1.0pt,
          cap: "butt",
          join: "miter"),
        closed: true),
      dx: 0in,
      dy: 0in)
    place(
      path(
        (0.84in, 0.7069375000000004in),
        (0.94in, 0.7069375000000004in),
        (1.04in, 0.7069375000000004in),
        fill: none,
        stroke: stroke(
          paint: rgb(
            12.156862745098039%,
            46.666666666666664%,
            70.58823529411765%,
            100.0%),
          thickness: 1.5pt,
          cap: "square",
          join: "round")),
      dx: 0in,
      dy: 0in)
    draw-text(
      [4 cores],
      dx: 1.12in,
      dy: 0.7419374999999997in,
      size: 10.0pt,
      alignment: left + bottom,
      baseline: true,
      angle: 360.0deg)
    place(
      path(
        (0.84in, 0.8536562500000002in),
        (0.94in, 0.8536562500000002in),
        (1.04in, 0.8536562500000002in),
        fill: none,
        stroke: stroke(
          paint: rgb(
            100.0%,
            49.80392156862745%,
            5.490196078431373%,
            100.0%),
          thickness: 1.5pt,
          cap: "square",
          join: "round")),
      dx: 0in,
      dy: 0in)
    draw-text(
      [16 cores],
      dx: 1.12in,
      dy: 0.8886562499999999in,
      size: 10.0pt,
      alignment: left + bottom,
      baseline: true,
      angle: 360.0deg)
    place(
      path(
        (0.84in, 1.000375in),
        (0.94in, 1.000375in),
        (1.04in, 1.000375in),
        fill: none,
        stroke: stroke(
          paint: rgb(
            17.254901960784313%,
            62.745098039215684%,
            17.254901960784313%,
            100.0%),
          thickness: 1.5pt,
          cap: "square",
          join: "round")),
      dx: 0in,
      dy: 0in)
    draw-text(
      [64 cores],
      dx: 1.12in,
      dy: 1.0353750000000002in,
      size: 10.0pt,
      alignment: left + bottom,
      baseline: true,
      angle: 360.0deg)
  },
  spacing: 0pt,
  above: 0pt,
  below: 0pt,
  width: 6.0in,
  height: 4.8in)